# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: monad-hyperindex
description: Local Monad explorer powered by HyperIndex
preload_handlers: true
unordered_multichain_mode: true
networks:
  - id: 10143
    start_block: 0
    contracts:
      - name: Placeholder
        address:
          - "0x0000000000000000000000000000000000000000"
        handler: src/EventHandlers.ts
        events:
          - event: Dummy(address indexed placeholder)
