type Block @index(fields: ["chainId", "number"]) {
  id: ID!
  chainId: Int! @index
  number: Int! @index
  hash: String! @index
  parentHash: String!
  timestamp: Timestamp! @index
  size: BigInt
  gasLimit: BigInt
  gasUsed: BigInt
  miner: String
  extraData: String
  baseFeePerGas: BigInt
}

type Transaction @index(fields: ["chainId", "blockNumber", "transactionIndex"]) {
  id: ID!
  hash: String! @index
  chainId: Int! @index
  block: Block!
  blockNumber: Int! @index
  transactionIndex: Int!
  from: String! @index
  to: String @index
  value: BigInt!
  input: String
  nonce: BigInt
  status: Int
  gas: BigInt
  gasPrice: BigInt
  gasUsed: BigInt
  maxFeePerGas: BigInt
  maxPriorityFeePerGas: BigInt
  effectiveGasPrice: BigInt
  cumulativeGasUsed: BigInt
  contractAddress: String @index
  kind: Int
  timestamp: Timestamp! @index
}

type ChainLog @index(fields: ["chainId", "blockNumber", "logIndex"]) {
  id: ID!
  chainId: Int! @index
  transaction: Transaction!
  blockNumber: Int! @index
  logIndex: Int! @index
  address: String! @index
  data: String!
  topic0: String
  topic1: String
  topic2: String
  topic3: String
  removed: Boolean
}
